/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mazgi_example_hmdbexample4android_JNIBridge */

#ifndef _Included_com_mazgi_example_hmdbexample4android_JNIBridge
#define _Included_com_mazgi_example_hmdbexample4android_JNIBridge

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_mazgi_example_hmdbexample4android_JNIBridge
 * Method:    execHMDatabase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mazgi_example_hmdbexample4android_JNIBridge_execHMDatabase
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif

#endif
